-- Exercise Library Expansion Phase 2: 206 → 406 exercises
-- Adds 200 new exercises across all 12 muscle groups and 7 equipment types
-- Fills gaps: missing equipment variations, competitor parity, full commercial gym coverage

-- ============================================================================
-- CHEST (+15 new → 36 total)
-- ============================================================================
INSERT INTO public.exercises (name_en, name_fr, muscle_primary, muscle_secondary, equipment, category, cues_en, cues_fr, difficulty, movement_pattern) VALUES
('Barbell Incline Bench Press', 'Développé incliné barre', 'chest', '{triceps,shoulders}', 'barbell', 'compound', 'Set bench to 30-45°. Unrack bar, lower to upper chest. Press up and slightly back. Retract shoulder blades throughout.', 'Réglez le banc à 30-45°. Descendez la barre vers le haut de la poitrine. Poussez vers le haut. Omoplates rétractées.', 'intermediate', 'push'),
('Barbell Floor Press', 'Développé couché au sol barre', 'chest', '{triceps,shoulders}', 'barbell', 'compound', 'Lie on floor, unrack bar. Lower until upper arms touch floor. Pause briefly, press up. Limits range for shoulder safety.', 'Allongé au sol, descendez jusqu''à ce que les bras touchent le sol. Pause, puis poussez. Limite l''amplitude pour protéger les épaules.', 'intermediate', 'push'),
('Dumbbell Incline Fly', 'Écarté incliné haltères', 'chest', '{}', 'dumbbell', 'isolation', 'Set bench to 30°. Arms extended above, slight elbow bend. Lower in wide arc until chest stretch. Squeeze back together.', 'Banc à 30°. Bras tendus, légère flexion. Descendez en arc large jusqu''à l''étirement. Contractez pour remonter.', 'beginner', 'isolation'),
('Dumbbell Floor Press', 'Développé couché au sol haltères', 'chest', '{triceps}', 'dumbbell', 'compound', 'Lie on floor, press dumbbells from chest. Lower until elbows touch floor. Pause, press up. Shoulder-friendly pressing.', 'Allongé au sol, poussez les haltères. Descendez jusqu''au sol. Pause, remontez. Bon pour les épaules.', 'beginner', 'push'),
('Cable Chest Press', 'Développé pectoraux poulie', 'chest', '{triceps,shoulders}', 'cable', 'compound', 'Cables at chest height, step forward. Press handles forward and together. Squeeze chest at full extension. Slow return.', 'Poulies à hauteur de poitrine, avancez. Poussez les poignées en avant. Contractez les pectoraux. Retour lent.', 'beginner', 'push'),
('Smith Machine Incline Bench Press', 'Développé incliné Smith machine', 'chest', '{triceps,shoulders}', 'machine', 'compound', 'Set bench at 30-45° under Smith bar. Unrack, lower to upper chest. Press along the guided path. Good for controlled overload.', 'Banc à 30-45° sous la barre Smith. Descendez vers le haut de la poitrine. Poussez le long du rail. Bon pour la surcharge contrôlée.', 'beginner', 'push'),
('Smith Machine Decline Bench Press', 'Développé décliné Smith machine', 'chest', '{triceps,shoulders}', 'machine', 'compound', 'Set bench at slight decline under Smith bar. Lower to lower chest. Press up along guided path.', 'Banc légèrement décliné sous la Smith. Descendez vers le bas de la poitrine. Poussez le long du rail.', 'beginner', 'push'),
('Decline Push-Up', 'Pompes déclinées', 'chest', '{triceps,shoulders}', 'bodyweight', 'compound', 'Feet elevated on bench or box. Hands on floor, lower chest toward ground. Press back up. Emphasizes upper chest.', 'Pieds surélevés sur un banc. Mains au sol, descendez la poitrine. Remontez. Accentue le haut des pectoraux.', 'intermediate', 'push'),
('Incline Push-Up', 'Pompes inclinées', 'chest', '{triceps,shoulders}', 'bodyweight', 'compound', 'Hands elevated on bench or box. Lower chest toward hands. Press back up. Easier than floor push-ups, great for beginners.', 'Mains surélevées sur un banc. Descendez la poitrine. Remontez. Plus facile que les pompes au sol.', 'beginner', 'push'),
('Weighted Push-Up', 'Pompes lestées', 'chest', '{triceps,shoulders}', 'bodyweight', 'compound', 'Place weight plate on upper back. Perform push-up with added resistance. Maintain straight body line throughout.', 'Placez un disque sur le haut du dos. Faites des pompes avec résistance ajoutée. Gardez le corps droit.', 'intermediate', 'push'),
('Wide Push-Up', 'Pompes écartées', 'chest', '{shoulders}', 'bodyweight', 'compound', 'Hands wider than shoulder-width. Lower chest to floor, elbows flare out. Press back up. Greater chest emphasis.', 'Mains plus larges que les épaules. Descendez, coudes écartés. Remontez. Plus d''accent sur les pectoraux.', 'beginner', 'push'),
('Ring Push-Up', 'Pompes aux anneaux', 'chest', '{triceps,shoulders}', 'bodyweight', 'compound', 'Hands on gymnastic rings, body straight. Lower chest between rings. Press back up. Instability increases chest activation.', 'Mains sur les anneaux, corps droit. Descendez entre les anneaux. Remontez. L''instabilité augmente l''activation.', 'intermediate', 'push'),
('Ring Dip', 'Dips aux anneaux', 'chest', '{triceps,shoulders}', 'bodyweight', 'compound', 'Support yourself on rings, arms locked. Lower until upper arms are parallel. Press back up. Lean forward for chest emphasis.', 'Supportez-vous sur les anneaux. Descendez jusqu''à la parallèle. Remontez. Penchez-vous pour cibler les pectoraux.', 'advanced', 'push'),
('Kettlebell Alternating Floor Press', 'Développé alterné au sol kettlebell', 'chest', '{triceps}', 'kettlebell', 'compound', 'Lie on floor with two kettlebells. Press one up while holding the other at chest. Alternate sides.', 'Allongé avec deux kettlebells. Poussez un côté pendant que l''autre reste à la poitrine. Alternez.', 'intermediate', 'push'),
('Band Chest Press', 'Développé pectoraux avec bande', 'chest', '{triceps,shoulders}', 'bands', 'compound', 'Anchor band behind you at chest height. Press forward until arms are extended. Squeeze chest. Control return.', 'Ancrez la bande derrière à hauteur de poitrine. Poussez en avant. Contractez les pectoraux. Retour contrôlé.', 'beginner', 'push');

-- ============================================================================
-- BACK (+22 new → 49 total)
-- ============================================================================
INSERT INTO public.exercises (name_en, name_fr, muscle_primary, muscle_secondary, equipment, category, cues_en, cues_fr, difficulty, movement_pattern) VALUES
('Barbell Deficit Deadlift', 'Soulevé de terre en déficit barre', 'back', '{glutes,hamstrings,quads}', 'barbell', 'compound', 'Stand on small platform or plates. Deadlift from increased range of motion. Strengthens the bottom position. Keep back flat.', 'Debout sur une plateforme. Soulevé de terre avec amplitude augmentée. Renforce la position basse. Dos plat.', 'advanced', 'hinge'),
('Barbell Meadows Row', 'Rowing Meadows barre', 'back', '{biceps}', 'barbell', 'compound', 'Landmine setup, perpendicular stance. Overhand grip on bar end. Row to hip, squeeze lat. Lower with control.', 'Configuration landmine, position perpendiculaire. Prise pronation sur le bout de la barre. Tirez vers la hanche. Descendez avec contrôle.', 'intermediate', 'pull'),
('Barbell Yates Row', 'Rowing Yates barre', 'back', '{biceps}', 'barbell', 'compound', 'Underhand grip, torso at ~70° angle. Pull bar to lower abs. Squeeze back at top. More upright than standard row.', 'Prise supination, torse à ~70°. Tirez la barre vers le bas des abdos. Contractez en haut. Plus droit que le rowing standard.', 'intermediate', 'pull'),
('Dumbbell Bent-Over Row', 'Rowing penché haltères', 'back', '{biceps}', 'dumbbell', 'compound', 'Hinge at hips, dumbbell in each hand. Row both to hips, squeeze shoulder blades. Lower with control. Keep back flat.', 'Penché aux hanches, un haltère dans chaque main. Tirez vers les hanches, serrez les omoplates. Dos plat.', 'intermediate', 'pull'),
('Dumbbell Deadlift', 'Soulevé de terre haltères', 'back', '{glutes,hamstrings,quads}', 'dumbbell', 'compound', 'Dumbbells at sides, feet hip-width. Hinge at hips and bend knees. Stand by driving hips forward. Keep dumbbells close.', 'Haltères le long du corps. Penchez les hanches, fléchissez les genoux. Levez-vous en poussant les hanches. Gardez les haltères proches.', 'beginner', 'hinge'),
('Cable Wide-Grip Seated Row', 'Rowing assis prise large poulie', 'back', '{biceps,shoulders}', 'cable', 'compound', 'Sit tall, wide-grip bar. Pull to lower chest, elbows wide. Squeeze shoulder blades. Slow return. Targets upper back.', 'Assis droit, barre large. Tirez vers le bas de la poitrine, coudes écartés. Serrez les omoplates. Cible le haut du dos.', 'beginner', 'pull'),
('Cable Single-Arm Row', 'Rowing unilatéral poulie', 'back', '{biceps}', 'cable', 'compound', 'Low pulley, single handle. Row to hip with one arm, rotate torso slightly. Squeeze lat. Slow return.', 'Poulie basse, poignée simple. Tirez vers la hanche, légère rotation du torse. Contractez le dorsal. Retour lent.', 'beginner', 'pull'),
('Cable Single-Arm Lat Pulldown', 'Tirage vertical unilatéral poulie', 'back', '{biceps}', 'cable', 'compound', 'High pulley, single handle. Pull down to shoulder, elbow close. Squeeze lat at bottom. Control the return.', 'Poulie haute, poignée simple. Tirez vers l''épaule, coude au corps. Contractez en bas. Retour contrôlé.', 'beginner', 'pull'),
('Cable Neutral-Grip Lat Pulldown', 'Tirage vertical prise neutre poulie', 'back', '{biceps}', 'cable', 'compound', 'V-bar or neutral-grip handle on high pulley. Pull to upper chest, elbows close. Squeeze lats. Slow return.', 'Barre en V sur poulie haute. Tirez vers le haut de la poitrine, coudes au corps. Contractez les dorsaux. Retour lent.', 'beginner', 'pull'),
('Machine Back Extension', 'Extension dorsale machine', 'back', '{glutes,hamstrings}', 'machine', 'compound', 'Sit in machine, pad against upper back. Extend torso backward against resistance. Squeeze lower back. Return with control.', 'Assis dans la machine, pad contre le haut du dos. Étendez le torse en arrière. Contractez le bas du dos. Retour contrôlé.', 'beginner', 'hinge'),
('Machine Reverse Hyperextension', 'Hyperextension inversée machine', 'back', '{glutes,hamstrings}', 'machine', 'compound', 'Lie face down on machine, hips at edge. Raise legs behind you against resistance. Squeeze glutes and lower back at top.', 'Allongé face vers le bas, hanches au bord. Montez les jambes contre la résistance. Contractez fessiers et bas du dos.', 'intermediate', 'hinge'),
('Machine Pullover', 'Pullover machine', 'back', '{chest}', 'machine', 'isolation', 'Sit in machine, elbows on pads above head. Pull pads down in arc to waist level. Squeeze lats. Slow return.', 'Assis, coudes sur les pads. Tirez les pads vers la taille en arc. Contractez les dorsaux. Retour lent.', 'beginner', 'pull'),
('Machine T-Bar Row', 'Rowing T-bar machine', 'back', '{biceps}', 'machine', 'compound', 'Chest against pad, grip handles. Row toward chest, squeeze shoulder blades. Lower with control. Chest support eliminates cheating.', 'Poitrine contre le support, saisissez les poignées. Tirez vers la poitrine. Descendez avec contrôle. Le support élimine l''élan.', 'beginner', 'pull'),
('Machine Lat Pulldown Wide-Grip', 'Tirage vertical prise large machine', 'back', '{biceps}', 'machine', 'compound', 'Wide grip on machine handles. Pull down to upper chest, elbows wide. Squeeze lats. Control the return.', 'Prise large sur les poignées. Tirez vers le haut de la poitrine. Contractez les dorsaux. Retour contrôlé.', 'beginner', 'pull'),
('Smith Machine Bent-Over Row', 'Rowing penché Smith machine', 'back', '{biceps}', 'machine', 'compound', 'Hinge at hips, grip Smith bar. Row to lower chest along guided path. Squeeze back. Lower with control.', 'Penché aux hanches, saisissez la barre Smith. Tirez vers le bas de la poitrine. Contractez le dos. Retour contrôlé.', 'beginner', 'pull'),
('Smith Machine Deadlift', 'Soulevé de terre Smith machine', 'back', '{glutes,hamstrings,quads}', 'machine', 'compound', 'Feet under Smith bar, hip-width. Hinge and grip bar. Stand by extending hips and knees. Lock out at top.', 'Pieds sous la barre Smith. Penchez-vous et saisissez. Levez-vous en étendant hanches et genoux. Verrouillez en haut.', 'beginner', 'hinge'),
('Weighted Pull-Up', 'Traction lestée', 'back', '{biceps}', 'bodyweight', 'compound', 'Add weight via belt or vest. Overhand grip, pull chin over bar. Squeeze lats. Lower with full control. Master bodyweight first.', 'Ajoutez du poids via ceinture ou gilet. Prise pronation, menton au-dessus. Contractez. Descendez avec contrôle.', 'advanced', 'pull'),
('Back Extension', 'Extension dorsale', 'back', '{glutes,hamstrings}', 'bodyweight', 'compound', 'Position in Roman chair, hips at pad edge. Lower torso toward floor. Raise back to horizontal, squeeze lower back. Do not hyperextend.', 'Sur la chaise romaine, hanches au bord. Descendez le torse. Remontez à l''horizontale. Ne pas hyper-étendre.', 'beginner', 'hinge'),
('Superman', 'Superman', 'back', '{glutes}', 'bodyweight', 'isolation', 'Lie face down, arms extended forward. Simultaneously lift arms, chest, and legs off floor. Hold briefly. Lower with control.', 'Allongé face vers le bas, bras tendus. Soulevez bras, poitrine et jambes simultanément. Maintenez. Redescendez.', 'beginner', 'hinge'),
('Kettlebell Deadlift', 'Soulevé de terre kettlebell', 'back', '{glutes,hamstrings}', 'kettlebell', 'compound', 'Kettlebell between feet. Hinge at hips, grip handle. Stand by driving hips forward. Squeeze glutes at top.', 'Kettlebell entre les pieds. Penchez les hanches, saisissez la poignée. Levez-vous en poussant les hanches. Contractez en haut.', 'beginner', 'hinge'),
('Band Seated Row', 'Rowing assis avec bande', 'back', '{biceps}', 'bands', 'compound', 'Sit on floor, band around feet. Pull handles to torso, squeeze shoulder blades. Slow return. Keep back straight.', 'Assis au sol, bande autour des pieds. Tirez vers le torse, serrez les omoplates. Retour lent. Dos droit.', 'beginner', 'pull'),
('Band Deadlift', 'Soulevé de terre avec bande', 'back', '{glutes,hamstrings}', 'bands', 'compound', 'Stand on band, grip handles at sides. Deadlift motion — hinge and stand. Squeeze glutes at top. Control descent.', 'Debout sur la bande, saisissez les poignées. Mouvement de soulevé de terre. Contractez les fessiers en haut. Retour contrôlé.', 'beginner', 'hinge');

-- ============================================================================
-- SHOULDERS (+18 new → 43 total)
-- ============================================================================
INSERT INTO public.exercises (name_en, name_fr, muscle_primary, muscle_secondary, equipment, category, cues_en, cues_fr, difficulty, movement_pattern) VALUES
('Barbell Seated Overhead Press', 'Développé militaire assis barre', 'shoulders', '{triceps}', 'barbell', 'compound', 'Sit on bench with back support. Unrack bar at collarbone. Press overhead to lockout. Lower with control.', 'Assis avec support dorsal. Décrochz la barre aux clavicules. Poussez au-dessus. Descendez avec contrôle.', 'intermediate', 'push'),
('Barbell Behind the Neck Press', 'Développé nuque barre', 'shoulders', '{triceps}', 'barbell', 'compound', 'Bar behind neck on traps. Press overhead to lockout. Lower to just above traps. Requires good shoulder mobility. Avoid if shoulder issues.', 'Barre derrière la nuque sur les trapèzes. Poussez au-dessus. Descendez au-dessus des trapèzes. Nécessite une bonne mobilité.', 'advanced', 'push'),
('Barbell Z Press', 'Z press barre', 'shoulders', '{triceps,abs}', 'barbell', 'compound', 'Sit on floor with legs extended. Press bar from shoulders overhead. No back support forces core engagement. Very strict pressing.', 'Assis au sol, jambes tendues. Poussez la barre des épaules. Sans support dorsal, le gainage est essentiel. Mouvement très strict.', 'advanced', 'push'),
('Barbell Bradford Press', 'Bradford press barre', 'shoulders', '{triceps}', 'barbell', 'compound', 'Alternate pressing bar from front to behind neck without full lockout. Continuous tension on delts. Light weight, high reps.', 'Alternez en poussant devant puis derrière la nuque sans verrouiller. Tension continue sur les deltoïdes. Poids léger, hautes répétitions.', 'intermediate', 'push'),
('Dumbbell Overhead Press', 'Développé militaire haltères', 'shoulders', '{triceps,abs}', 'dumbbell', 'compound', 'Stand with dumbbells at shoulder height. Press overhead to lockout. Core engaged throughout. Lower with control.', 'Debout, haltères aux épaules. Poussez au-dessus. Gainage constant. Descendez avec contrôle.', 'intermediate', 'push'),
('Dumbbell Lu Raise', 'Lu raise haltères', 'shoulders', '{}', 'dumbbell', 'isolation', 'Perform lateral raise to shoulder height, then rotate arms to overhead position. Reverse the motion. Combines lateral raise and press.', 'Élévation latérale à hauteur d''épaules, puis rotation vers le haut. Inversez le mouvement. Combine élévation et développé.', 'intermediate', 'isolation'),
('Dumbbell W-Raise', 'W-raise haltères', 'shoulders', '{back}', 'dumbbell', 'isolation', 'Hinge forward. Raise dumbbells out and up forming a W shape with arms. Squeeze rear delts and rotator cuff. Lower with control.', 'Penché en avant. Montez les haltères en formant un W. Contractez les deltoïdes postérieurs. Descendez avec contrôle.', 'beginner', 'isolation'),
('Dumbbell Shoulder External Rotation', 'Rotation externe épaule haltère', 'shoulders', '{}', 'dumbbell', 'isolation', 'Lie on side, elbow at 90° on hip. Rotate forearm upward. Lower with control. Strengthens rotator cuff. Use light weight.', 'Allongé sur le côté, coude à 90° sur la hanche. Tournez l''avant-bras vers le haut. Renforce la coiffe des rotateurs. Poids léger.', 'beginner', 'rotation'),
('Cable Front Raise', 'Élévation frontale poulie', 'shoulders', '{}', 'cable', 'isolation', 'Low pulley, straight bar or handle. Raise to shoulder height, arms straight. Lower with control. Constant cable tension.', 'Poulie basse, barre ou poignée. Montez à hauteur d''épaules, bras tendus. Descendez avec contrôle. Tension constante.', 'beginner', 'isolation'),
('Cable Rear Delt Row', 'Rowing deltoïde postérieur poulie', 'shoulders', '{back}', 'cable', 'compound', 'Cable at face height, rope attachment. Pull toward face with elbows high and wide. Squeeze rear delts. Slow return.', 'Poulie à hauteur du visage, corde. Tirez vers le visage, coudes hauts. Contractez les deltoïdes postérieurs. Retour lent.', 'beginner', 'pull'),
('Machine Lateral Raise', 'Élévation latérale machine', 'shoulders', '{}', 'machine', 'isolation', 'Sit in machine, pads against outer arms. Raise arms to shoulder height against resistance. Lower with control.', 'Assis, pads contre les bras. Montez à hauteur d''épaules contre la résistance. Descendez avec contrôle.', 'beginner', 'isolation'),
('Smith Machine Overhead Press', 'Développé militaire Smith machine', 'shoulders', '{triceps}', 'machine', 'compound', 'Sit or stand under Smith bar. Press overhead along guided path. Lower to chin level. Good for controlled overload.', 'Assis ou debout sous la barre Smith. Poussez le long du rail. Descendez au menton. Bon pour la surcharge contrôlée.', 'beginner', 'push'),
('Smith Machine Behind the Neck Press', 'Développé nuque Smith machine', 'shoulders', '{triceps}', 'machine', 'compound', 'Sit under Smith bar, bar behind neck. Press up along guided path. Lower to just above traps. Requires good mobility.', 'Assis, barre derrière la nuque. Poussez le long du rail. Descendez au-dessus des trapèzes. Bonne mobilité requise.', 'intermediate', 'push'),
('Landmine Lateral Raise', 'Élévation latérale landmine', 'shoulders', '{}', 'barbell', 'isolation', 'Hold barbell end at hip. Raise across body to shoulder height. Lower with control. Unique resistance curve.', 'Tenez le bout de la barre à la hanche. Montez en travers du corps à hauteur d''épaule. Descendez avec contrôle. Courbe de résistance unique.', 'intermediate', 'isolation'),
('Dumbbell Cuban Press', 'Cuban press haltères', 'shoulders', '{}', 'dumbbell', 'isolation', 'Upright row to elbows high, then externally rotate to press position, then press overhead. Reverse on the way down. Excellent for rotator cuff.', 'Tirage vertical coudes hauts, puis rotation externe, puis développé. Inversez en descendant. Excellent pour la coiffe des rotateurs.', 'intermediate', 'rotation'),
('Kettlebell Halo', 'Halo kettlebell', 'shoulders', '{abs}', 'kettlebell', 'isolation', 'Hold kettlebell upside down at chest. Circle it around your head. Reverse direction each set. Great for shoulder mobility.', 'Tenez le kettlebell inversé à la poitrine. Faites-le tourner autour de la tête. Changez de sens. Excellent pour la mobilité.', 'beginner', 'rotation'),
('Band External Rotation', 'Rotation externe avec bande', 'shoulders', '{}', 'bands', 'isolation', 'Anchor band at elbow height. Elbow at 90° at your side. Rotate forearm outward against resistance. Slow return.', 'Ancrez la bande à hauteur du coude. Coude à 90° au corps. Tournez l''avant-bras vers l''extérieur. Retour lent.', 'beginner', 'rotation'),
('Band Internal Rotation', 'Rotation interne avec bande', 'shoulders', '{}', 'bands', 'isolation', 'Anchor band at elbow height. Elbow at 90° at your side. Rotate forearm inward against resistance. Slow return.', 'Ancrez la bande à hauteur du coude. Coude à 90° au corps. Tournez l''avant-bras vers l''intérieur. Retour lent.', 'beginner', 'rotation');

-- ============================================================================
-- BICEPS (+15 new → 29 total)
-- ============================================================================
INSERT INTO public.exercises (name_en, name_fr, muscle_primary, muscle_secondary, equipment, category, cues_en, cues_fr, difficulty, movement_pattern) VALUES
('Dumbbell Curl', 'Curl haltères', 'biceps', '{}', 'dumbbell', 'isolation', 'Stand with dumbbells at sides, palms forward. Curl both up to shoulders, elbows pinned. Lower with full control.', 'Debout, haltères le long du corps, paumes en avant. Montez aux épaules, coudes fixes. Descendez avec contrôle.', 'beginner', 'pull'),
('Dumbbell Preacher Curl', 'Curl pupitre haltère', 'biceps', '{}', 'dumbbell', 'isolation', 'Arm on preacher pad, dumbbell in hand. Curl up, squeeze at top. Lower with full control. Isolates the biceps peak.', 'Bras sur le pupitre, haltère en main. Montez, contractez. Descendez avec contrôle. Isole le pic du biceps.', 'beginner', 'pull'),
('Dumbbell Spider Curl', 'Spider curl haltères', 'biceps', '{}', 'dumbbell', 'isolation', 'Lie chest-down on incline bench. Arms hang straight. Curl dumbbells up, squeeze hard at top. No momentum possible.', 'Poitrine contre banc incliné. Bras pendants. Montez les haltères, contractez fort. Aucun élan possible.', 'intermediate', 'pull'),
('Dumbbell Reverse Curl', 'Curl inversé haltères', 'biceps', '{forearms}', 'dumbbell', 'isolation', 'Overhand grip on dumbbells. Curl up keeping palms down. Lower with control. Targets brachialis and forearms.', 'Prise pronation sur les haltères. Montez paumes vers le bas. Descendez avec contrôle. Cible le brachial et les avant-bras.', 'beginner', 'pull'),
('Dumbbell Cross-Body Curl', 'Curl croisé haltère', 'biceps', '{}', 'dumbbell', 'isolation', 'Hold dumbbell at side. Curl across body toward opposite shoulder. Squeeze at top. Lower with control. Hits the long head.', 'Haltère le long du corps. Montez en travers vers l''épaule opposée. Contractez. Descendez avec contrôle. Cible le long biceps.', 'beginner', 'pull'),
('Cable Overhead Curl', 'Curl au-dessus poulie haute', 'biceps', '{}', 'cable', 'isolation', 'High pulleys on each side. Arms extended at shoulder height. Curl toward ears, squeeze biceps hard. Slow return.', 'Poulies hautes de chaque côté. Bras tendus à hauteur d''épaules. Montez vers les oreilles. Contractez fort. Retour lent.', 'intermediate', 'pull'),
('Cable Bayesian Curl', 'Curl Bayesian poulie', 'biceps', '{}', 'cable', 'isolation', 'Low pulley behind you, single handle. Arm extended behind body. Curl forward and up. Emphasizes stretched position of biceps.', 'Poulie basse derrière vous, poignée simple. Bras tendu derrière. Montez en avant. Accentue la position étirée du biceps.', 'intermediate', 'pull'),
('Cable Preacher Curl', 'Curl pupitre poulie', 'biceps', '{}', 'cable', 'isolation', 'Low pulley, preacher bench. Curl bar up, squeeze at top. Lower with control. Constant tension from cable.', 'Poulie basse, pupitre. Montez la barre, contractez. Descendez avec contrôle. Tension constante du câble.', 'beginner', 'pull'),
('Cable Single-Arm Curl', 'Curl unilatéral poulie', 'biceps', '{}', 'cable', 'isolation', 'Low pulley, single handle. Curl one arm up, elbow pinned. Squeeze at top. Slow negative. Alternate sides.', 'Poulie basse, poignée simple. Montez un bras, coude fixe. Contractez. Négatif lent. Alternez.', 'beginner', 'pull'),
('Machine Bicep Curl', 'Curl biceps machine', 'biceps', '{}', 'machine', 'isolation', 'Sit in curl machine, arms on pad. Curl handles up, squeeze at top. Lower with control. Consistent resistance throughout.', 'Assis dans la machine, bras sur le pad. Montez, contractez. Descendez avec contrôle. Résistance constante.', 'beginner', 'pull'),
('Barbell Wide-Grip Curl', 'Curl prise large barre', 'biceps', '{}', 'barbell', 'isolation', 'Grip barbell wider than shoulders. Curl up, elbows pinned. Squeeze at top. Emphasizes the short head of biceps.', 'Saisissez la barre plus large que les épaules. Montez, coudes fixes. Contractez. Accentue le court biceps.', 'beginner', 'pull'),
('Weighted Chin-Up', 'Traction supination lestée', 'biceps', '{back}', 'bodyweight', 'compound', 'Add weight via belt or vest. Underhand grip, pull chin over bar. Squeeze biceps. Lower with control. Master bodyweight first.', 'Ajoutez du poids. Prise supination, menton au-dessus. Contractez les biceps. Descendez avec contrôle. Maîtrisez le poids du corps d''abord.', 'advanced', 'pull'),
('Bodyweight Ring Curl', 'Curl aux anneaux', 'biceps', '{}', 'bodyweight', 'isolation', 'Hang from rings, body angled. Curl body toward rings by bending elbows. Extend back to start. Adjust angle for difficulty.', 'Suspendu aux anneaux, corps incliné. Montez vers les anneaux en fléchissant. Revenez. Ajustez l''angle pour la difficulté.', 'intermediate', 'pull'),
('Kettlebell Hammer Curl', 'Curl marteau kettlebell', 'biceps', '{forearms}', 'kettlebell', 'isolation', 'Hold kettlebell by horns, neutral grip. Curl up to chest, squeeze. Lower with control. Offset weight challenges grip.', 'Tenez le kettlebell par les cornes, prise neutre. Montez à la poitrine. Descendez avec contrôle. Le poids décalé travaille la prise.', 'beginner', 'pull'),
('Band Preacher Curl', 'Curl pupitre avec bande', 'biceps', '{}', 'bands', 'isolation', 'Anchor band low, arm on preacher pad. Curl against resistance, squeeze at top. Slow negative. Constant tension.', 'Ancrez la bande en bas, bras sur le pupitre. Montez contre la résistance. Contractez. Négatif lent.', 'beginner', 'pull');

-- ============================================================================
-- TRICEPS (+14 new → 29 total)
-- ============================================================================
INSERT INTO public.exercises (name_en, name_fr, muscle_primary, muscle_secondary, equipment, category, cues_en, cues_fr, difficulty, movement_pattern) VALUES
('Dumbbell Lying Tricep Extension', 'Extension triceps allongé haltères', 'triceps', '{}', 'dumbbell', 'isolation', 'Lie flat, dumbbells above chest. Lower toward ears by bending elbows. Extend back up. Keep upper arms stationary.', 'Allongé, haltères au-dessus. Descendez vers les oreilles en fléchissant. Remontez. Gardez les bras fixes.', 'intermediate', 'push'),
('Dumbbell Close-Grip Press', 'Développé prise serrée haltères', 'triceps', '{chest}', 'dumbbell', 'compound', 'Lie flat, press dumbbells together above chest. Keep elbows tucked. Lower to chest, press up. Emphasizes triceps.', 'Allongé, pressez les haltères ensemble au-dessus. Coudes au corps. Descendez, poussez. Accentue les triceps.', 'beginner', 'push'),
('Cable Rope Pushdown', 'Extension triceps corde poulie haute', 'triceps', '{}', 'cable', 'isolation', 'High pulley, rope attachment. Push down and spread rope at bottom. Squeeze triceps. Control the return. Elbows pinned.', 'Poulie haute, corde. Poussez et écartez la corde en bas. Contractez les triceps. Retour contrôlé. Coudes fixes.', 'beginner', 'push'),
('Cable Tricep Kickback', 'Kickback triceps poulie', 'triceps', '{}', 'cable', 'isolation', 'Low pulley, single handle. Hinge forward, extend arm back. Squeeze tricep. Constant cable tension throughout.', 'Poulie basse, poignée simple. Penchez-vous, étendez le bras. Contractez le triceps. Tension constante du câble.', 'beginner', 'push'),
('Cable Cross-Body Extension', 'Extension croisée poulie', 'triceps', '{}', 'cable', 'isolation', 'High pulley, single handle. Extend arm across body and down. Squeeze tricep. Slow return. Unique angle of resistance.', 'Poulie haute, poignée simple. Étendez le bras en travers et vers le bas. Contractez. Retour lent. Angle de résistance unique.', 'beginner', 'push'),
('Machine Seated Tricep Extension', 'Extension triceps assis machine', 'triceps', '{}', 'machine', 'isolation', 'Sit in machine, elbows on pad. Extend arms down against resistance. Squeeze at full extension. Slow return.', 'Assis, coudes sur le pad. Étendez les bras contre la résistance. Contractez en extension complète. Retour lent.', 'beginner', 'push'),
('Machine Tricep Pushdown', 'Extension triceps machine verticale', 'triceps', '{}', 'machine', 'isolation', 'Stand at machine, grip bar. Push down until arms are extended. Squeeze triceps. Slow return. Elbows stay at sides.', 'Debout, saisissez la barre. Poussez jusqu''à l''extension. Contractez les triceps. Retour lent. Coudes au corps.', 'beginner', 'push'),
('Smith Machine Close-Grip Bench Press', 'Développé prise serrée Smith machine', 'triceps', '{chest,shoulders}', 'machine', 'compound', 'Lie under Smith bar, narrow grip. Lower to lower chest, elbows tucked. Press up along guided path.', 'Allongé sous la Smith, prise serrée. Descendez, coudes au corps. Poussez le long du rail.', 'beginner', 'push'),
('Bodyweight Tricep Extension', 'Extension triceps au poids du corps', 'triceps', '{}', 'bodyweight', 'isolation', 'Hands on bar or bench at chest height. Lean forward, lower forehead toward bar by bending elbows. Extend back up. Body stays straight.', 'Mains sur une barre à hauteur de poitrine. Penchez-vous, descendez le front vers la barre. Remontez. Corps droit.', 'intermediate', 'push'),
('Ring Tricep Dip', 'Dips triceps aux anneaux', 'triceps', '{chest,shoulders}', 'bodyweight', 'compound', 'Support on rings, body upright. Lower until upper arms parallel, elbows close. Press back up. Instability increases demand.', 'Supportez-vous sur les anneaux, corps droit. Descendez, coudes au corps. Remontez. L''instabilité augmente la difficulté.', 'advanced', 'push'),
('Kettlebell Skull Crusher', 'Barre au front kettlebell', 'triceps', '{}', 'kettlebell', 'isolation', 'Lie flat, hold kettlebell over chest. Lower toward forehead by bending elbows. Extend back up. Keep upper arms vertical.', 'Allongé, kettlebell au-dessus. Descendez vers le front en fléchissant. Remontez. Gardez les bras verticaux.', 'intermediate', 'push'),
('Band Pushdown', 'Extension triceps bande vers le bas', 'triceps', '{}', 'bands', 'isolation', 'Anchor band overhead. Grip ends, push down until arms extended. Squeeze triceps at bottom. Slow return.', 'Ancrez la bande en hauteur. Saisissez, poussez vers le bas. Contractez les triceps. Retour lent.', 'beginner', 'push'),
('Band Kickback', 'Kickback avec bande', 'triceps', '{}', 'bands', 'isolation', 'Step on band, hinge forward. Extend arm back against resistance. Squeeze tricep. Lower with control.', 'Debout sur la bande, penché. Étendez le bras contre la résistance. Contractez. Descendez avec contrôle.', 'beginner', 'push'),
('Barbell Overhead Tricep Extension', 'Extension triceps au-dessus barre', 'triceps', '{}', 'barbell', 'isolation', 'Stand or sit, bar overhead. Lower behind head by bending elbows. Extend back up. Keep elbows close and pointing up.', 'Debout ou assis, barre au-dessus. Descendez derrière la tête. Remontez. Gardez les coudes proches et vers le haut.', 'intermediate', 'push');

-- ============================================================================
-- QUADS (+20 new → 45 total)
-- ============================================================================
INSERT INTO public.exercises (name_en, name_fr, muscle_primary, muscle_secondary, equipment, category, cues_en, cues_fr, difficulty, movement_pattern) VALUES
('Barbell Overhead Squat', 'Squat barre au-dessus', 'quads', '{glutes,shoulders,abs}', 'barbell', 'compound', 'Snatch-grip bar overhead, arms locked. Squat deep with bar balanced. Requires excellent mobility. Start with PVC pipe to learn.', 'Barre au-dessus en prise d''arraché. Descendez avec la barre en équilibre. Nécessite une excellente mobilité. Commencez avec un bâton.', 'advanced', 'squat'),
('Barbell Box Squat', 'Squat sur box barre', 'quads', '{glutes,hamstrings}', 'barbell', 'compound', 'Squat to a box behind you. Sit briefly, then drive up. Teaches proper depth and hip hinge. Good for building explosive strength.', 'Descendez sur une box. Asseyez-vous brièvement, puis remontez. Enseigne la bonne profondeur. Bon pour l''explosivité.', 'intermediate', 'squat'),
('Barbell Bulgarian Split Squat', 'Squat bulgare barre', 'quads', '{glutes,hamstrings}', 'barbell', 'compound', 'Bar on upper back, rear foot on bench. Squat down on front leg until thigh is parallel. Drive through front heel.', 'Barre sur le haut du dos, pied arrière sur un banc. Descendez jusqu''à la parallèle. Poussez avec le talon avant.', 'advanced', 'squat'),
('Barbell Pause Squat', 'Squat avec pause barre', 'quads', '{glutes,hamstrings}', 'barbell', 'compound', 'Back squat with a 2-3 second pause at the bottom. No bouncing. Drive up from dead stop. Builds strength out of the hole.', 'Squat avec pause de 2-3 secondes en bas. Pas de rebond. Remontez depuis l''arrêt. Renforce la position basse.', 'intermediate', 'squat'),
('Barbell Split Squat', 'Squat fendu barre', 'quads', '{glutes}', 'barbell', 'compound', 'Bar on upper back, staggered stance. Lower until front thigh is parallel. Push up through front foot. Both feet stay on floor.', 'Barre sur le dos, position décalée. Descendez à la parallèle. Poussez avec le pied avant. Les deux pieds restent au sol.', 'intermediate', 'squat'),
('Dumbbell Squat', 'Squat haltères', 'quads', '{glutes}', 'dumbbell', 'compound', 'Hold dumbbells at sides. Squat to parallel or below, chest up. Stand by driving through heels. Simple and effective.', 'Haltères le long du corps. Descendez en parallèle, poitrine haute. Remontez en poussant avec les talons.', 'beginner', 'squat'),
('Dumbbell Sumo Squat', 'Squat sumo haltères', 'quads', '{glutes}', 'dumbbell', 'compound', 'Wide stance, toes out. Hold dumbbell hanging between legs. Squat deep, knees track over toes. Stand up, squeeze glutes.', 'Position large, pointes écartées. Haltère entre les jambes. Descendez, genoux sur les orteils. Contractez les fessiers.', 'beginner', 'squat'),
('Dumbbell Front Squat', 'Squat avant haltères', 'quads', '{glutes,abs}', 'dumbbell', 'compound', 'Hold dumbbells at shoulders, elbows up. Squat deep with upright torso. Drive through whole foot. Engages core heavily.', 'Haltères aux épaules, coudes hauts. Descendez avec le torse droit. Poussez avec tout le pied. Fort gainage.', 'intermediate', 'squat'),
('Machine Pendulum Squat', 'Squat pendulaire machine', 'quads', '{glutes}', 'machine', 'compound', 'Position in machine, shoulders under pads. Squat along pendulum arc. Drive up through legs. Reduces spinal loading.', 'Positionnez-vous, épaules sous les pads. Descendez le long de l''arc. Poussez avec les jambes. Réduit la charge vertébrale.', 'beginner', 'squat'),
('Machine V-Squat', 'V-squat machine', 'quads', '{glutes}', 'machine', 'compound', 'Stand on platform, back against pad. Squat deep along guided path. Drive up through legs. Targets quads with back support.', 'Debout sur la plateforme, dos contre le pad. Descendez le long du rail. Poussez. Cible les quadriceps avec support.', 'beginner', 'squat'),
('Machine Belt Squat', 'Squat ceinture machine', 'quads', '{glutes}', 'machine', 'compound', 'Attach belt at hips, stand on platforms. Squat deep — load through hips, not spine. Drive up. Excellent for back issues.', 'Attachez la ceinture aux hanches. Descendez — charge via les hanches, pas la colonne. Excellent pour les problèmes de dos.', 'beginner', 'squat'),
('Smith Machine Lunge', 'Fente Smith machine', 'quads', '{glutes,hamstrings}', 'machine', 'compound', 'Bar on upper back, one foot forward. Lunge down until front thigh parallel. Push back up. Guided path for stability.', 'Barre sur le dos, un pied en avant. Descendez en fente. Remontez. Rail guidé pour la stabilité.', 'beginner', 'squat'),
('Smith Machine Front Squat', 'Squat avant Smith machine', 'quads', '{glutes,abs}', 'machine', 'compound', 'Bar on front delts, arms crossed or clean grip. Squat along guided path. Drive up. Good for learning front squat pattern.', 'Barre sur les deltoïdes, bras croisés. Descendez le long du rail. Remontez. Bon pour apprendre le squat avant.', 'beginner', 'squat'),
('Smith Machine Bulgarian Split Squat', 'Squat bulgare Smith machine', 'quads', '{glutes,hamstrings}', 'machine', 'compound', 'Rear foot on bench, bar on upper back. Squat on front leg along guided path. Stable and effective for quad development.', 'Pied arrière sur banc, barre sur le dos. Descendez le long du rail. Stable et efficace pour les quadriceps.', 'intermediate', 'squat'),
('Bodyweight Lunge', 'Fente au poids du corps', 'quads', '{glutes,hamstrings}', 'bodyweight', 'compound', 'Step forward, lower until front thigh parallel. Push back to standing through front heel. Keep torso upright. Alternate legs.', 'Avancez, descendez à la parallèle. Revenez en poussant avec le talon. Torse droit. Alternez les jambes.', 'beginner', 'squat'),
('Bodyweight Reverse Lunge', 'Fente arrière au poids du corps', 'quads', '{glutes}', 'bodyweight', 'compound', 'Step backward, lower until front thigh parallel. Push back to standing through front foot. Easier on knees than forward lunge.', 'Reculez, descendez à la parallèle. Revenez en poussant avec le pied avant. Plus doux pour les genoux.', 'beginner', 'squat'),
('Bodyweight Step-Up', 'Step-up au poids du corps', 'quads', '{glutes}', 'bodyweight', 'compound', 'One foot on bench or box. Drive through elevated foot to stand on top. Step down with control. Alternate legs.', 'Un pied sur le banc. Poussez pour monter. Redescendez avec contrôle. Alternez les jambes.', 'beginner', 'squat'),
('Bodyweight Wall Sit', 'Chaise au mur', 'quads', '{}', 'bodyweight', 'isolation', 'Back flat against wall, slide down to 90° knee bend. Hold position. Thighs parallel to floor. Breathe steadily. Build time gradually.', 'Dos plat contre le mur, descendez à 90°. Maintenez la position. Cuisses parallèles au sol. Respirez régulièrement.', 'beginner', 'squat'),
('Kettlebell Lunge', 'Fente kettlebell', 'quads', '{glutes,hamstrings}', 'kettlebell', 'compound', 'Hold kettlebells at sides or in rack position. Step forward into lunge. Drive back through front heel. Alternate legs.', 'Kettlebells le long du corps ou en position rack. Avancez en fente. Revenez en poussant. Alternez.', 'beginner', 'squat'),
('Band Lunge', 'Fente avec bande', 'quads', '{glutes}', 'bands', 'compound', 'Stand on band, loop over shoulders. Step forward into lunge against resistance. Push back to start. Alternate legs.', 'Debout sur la bande, passez-la sur les épaules. Fente en avant contre la résistance. Revenez. Alternez.', 'beginner', 'squat');

-- ============================================================================
-- HAMSTRINGS (+15 new → 29 total)
-- ============================================================================
INSERT INTO public.exercises (name_en, name_fr, muscle_primary, muscle_secondary, equipment, category, cues_en, cues_fr, difficulty, movement_pattern) VALUES
('Barbell Stiff-Leg Deadlift', 'Soulevé de terre jambes tendues barre', 'hamstrings', '{glutes,back}', 'barbell', 'compound', 'Grip barbell, legs nearly straight. Hinge at hips, lower bar along legs. Feel deep hamstring stretch. Stand by driving hips forward.', 'Saisissez la barre, jambes quasi tendues. Penchez les hanches, descendez le long des jambes. Sentez l''étirement. Poussez les hanches.', 'intermediate', 'hinge'),
('Dumbbell Romanian Deadlift', 'Soulevé de terre roumain haltères', 'hamstrings', '{glutes,back}', 'dumbbell', 'compound', 'Hold dumbbells in front, slight knee bend. Hinge at hips, lower along legs to mid-shin. Drive hips forward to stand. Keep back flat.', 'Haltères devant, légère flexion. Penchez les hanches, descendez au milieu du tibia. Poussez les hanches. Dos plat.', 'intermediate', 'hinge'),
('Dumbbell Leg Curl', 'Leg curl haltère', 'hamstrings', '{}', 'dumbbell', 'isolation', 'Lie face down on bench, dumbbell held between feet. Curl heels toward glutes. Squeeze at top. Lower with control.', 'Allongé face vers le bas, haltère entre les pieds. Montez les talons vers les fessiers. Contractez. Descendez avec contrôle.', 'beginner', 'isolation'),
('Cable Leg Curl', 'Leg curl poulie', 'hamstrings', '{}', 'cable', 'isolation', 'Ankle cuff on low pulley, face away. Curl heel toward glute against resistance. Squeeze. Slow return. Stand on one leg.', 'Bracelet de cheville sur poulie basse. Montez le talon vers le fessier. Contractez. Retour lent. Debout sur une jambe.', 'beginner', 'isolation'),
('Cable Single-Leg Romanian Deadlift', 'Soulevé de terre roumain unilatéral poulie', 'hamstrings', '{glutes,back}', 'cable', 'compound', 'Low pulley, single handle. Single-leg hinge, free leg extends behind. Lower handle toward floor. Drive hip forward to stand.', 'Poulie basse, poignée simple. Penchez sur une jambe, l''autre s''étend derrière. Descendez vers le sol. Poussez la hanche.', 'intermediate', 'hinge'),
('Machine Standing Leg Curl', 'Leg curl debout machine', 'hamstrings', '{}', 'machine', 'isolation', 'Stand on one leg, pad behind ankle. Curl heel toward glute. Squeeze at top. Slow return. Alternate legs.', 'Debout sur une jambe, pad derrière la cheville. Montez vers le fessier. Contractez. Retour lent. Alternez.', 'beginner', 'isolation'),
('Machine Single-Leg Curl', 'Leg curl unilatéral machine', 'hamstrings', '{}', 'machine', 'isolation', 'Lying or seated machine, one leg at a time. Curl heel toward glute. Squeeze. Slow return. Corrects imbalances.', 'Machine allongée ou assise, une jambe. Montez vers le fessier. Contractez. Retour lent. Corrige les déséquilibres.', 'beginner', 'isolation'),
('Machine Glute-Ham Raise', 'Glute-ham raise machine', 'hamstrings', '{glutes,back}', 'machine', 'compound', 'Position in GHD machine, feet locked. Lower torso forward. Pull back up using hamstrings and glutes. Keep hips extended throughout.', 'Positionné dans la machine GHD, pieds bloqués. Descendez en avant. Remontez avec ischio-jambiers et fessiers. Hanches tendues.', 'advanced', 'hinge'),
('Smith Machine Romanian Deadlift', 'Soulevé de terre roumain Smith machine', 'hamstrings', '{glutes,back}', 'machine', 'compound', 'Grip Smith bar, slight knee bend. Hinge at hips, lower along guided path. Drive hips forward to stand. Guided path helps form.', 'Saisissez la barre Smith, légère flexion. Penchez les hanches le long du rail. Poussez les hanches. Le rail aide la technique.', 'beginner', 'hinge'),
('Smith Machine Good Morning', 'Good morning Smith machine', 'hamstrings', '{glutes,back}', 'machine', 'compound', 'Bar on upper back in Smith machine. Hinge at hips, lower torso to near parallel. Drive hips forward to stand. Guided and safe.', 'Barre sur le haut du dos. Penchez le torse vers la parallèle. Poussez les hanches. Guidé et sécuritaire.', 'beginner', 'hinge'),
('Bodyweight Good Morning', 'Good morning au poids du corps', 'hamstrings', '{glutes,back}', 'bodyweight', 'compound', 'Hands behind head or crossed on chest. Hinge at hips, lower torso. Feel hamstring stretch. Stand by driving hips forward.', 'Mains derrière la tête ou croisées. Penchez les hanches, descendez le torse. Sentez l''étirement. Poussez les hanches.', 'beginner', 'hinge'),
('Bodyweight Single-Leg Romanian Deadlift', 'Soulevé de terre roumain unilatéral au poids du corps', 'hamstrings', '{glutes}', 'bodyweight', 'compound', 'Stand on one leg. Hinge at hips, free leg extends behind. Reach toward floor. Drive hip forward to stand. Great for balance.', 'Debout sur une jambe. Penchez les hanches, l''autre jambe s''étend. Descendez vers le sol. Poussez la hanche. Bon pour l''équilibre.', 'intermediate', 'hinge'),
('Kettlebell Romanian Deadlift', 'Soulevé de terre roumain kettlebell', 'hamstrings', '{glutes,back}', 'kettlebell', 'compound', 'Hold kettlebell in front, slight knee bend. Hinge at hips, lower to mid-shin. Drive hips forward. Keep back flat.', 'Kettlebell devant, légère flexion. Penchez les hanches au milieu du tibia. Poussez les hanches. Dos plat.', 'beginner', 'hinge'),
('Band Romanian Deadlift', 'Soulevé de terre roumain avec bande', 'hamstrings', '{glutes}', 'bands', 'compound', 'Stand on band, grip handles. Hinge at hips against resistance. Drive hips forward to stand. Constant tension.', 'Debout sur la bande, saisissez. Penchez les hanches contre la résistance. Poussez les hanches. Tension constante.', 'beginner', 'hinge'),
('Band Pull-Through', 'Pull-through avec bande', 'hamstrings', '{glutes}', 'bands', 'compound', 'Anchor band low behind you. Straddle band, hinge forward. Drive hips forward to stand, squeezing glutes. Mimics cable pull-through.', 'Ancrez la bande derrière en bas. Enjambez, penchez-vous. Poussez les hanches, contractez les fessiers. Imite le pull-through poulie.', 'beginner', 'hinge');

-- ============================================================================
-- GLUTES (+20 new → 35 total)
-- ============================================================================
INSERT INTO public.exercises (name_en, name_fr, muscle_primary, muscle_secondary, equipment, category, cues_en, cues_fr, difficulty, movement_pattern) VALUES
('Barbell Reverse Lunge', 'Fente arrière barre', 'glutes', '{quads,hamstrings}', 'barbell', 'compound', 'Bar on upper back. Step backward into lunge. Lower until front thigh parallel. Drive through front heel to stand. More glute emphasis than forward lunge.', 'Barre sur le dos. Reculez en fente. Descendez à la parallèle. Poussez avec le talon avant. Plus de fessiers que la fente avant.', 'intermediate', 'squat'),
('Barbell Glute Bridge', 'Pont fessier barre', 'glutes', '{hamstrings}', 'barbell', 'compound', 'Lie on floor, bar over hips. Feet flat, knees bent. Drive hips up, squeeze glutes at top. Lower with control. Shorter range than hip thrust.', 'Allongé, barre sur les hanches. Pieds à plat. Poussez les hanches, contractez. Descendez avec contrôle. Moins d''amplitude que le hip thrust.', 'intermediate', 'hinge'),
('Barbell Curtsy Lunge', 'Fente croisée barre', 'glutes', '{quads}', 'barbell', 'compound', 'Bar on upper back. Step one foot behind and across. Lower into a curtsy position. Drive through front heel. Targets glute medius.', 'Barre sur le dos. Croisez un pied derrière. Descendez en position croisée. Poussez avec le talon. Cible le moyen fessier.', 'intermediate', 'squat'),
('Dumbbell Hip Thrust', 'Hip thrust haltère', 'glutes', '{hamstrings}', 'dumbbell', 'compound', 'Upper back on bench, dumbbell over hips. Drive hips up until body straight. Squeeze glutes hard at top. Lower with control.', 'Haut du dos sur le banc, haltère sur les hanches. Poussez les hanches. Contractez fort. Descendez avec contrôle.', 'beginner', 'hinge'),
('Dumbbell Sumo Deadlift', 'Soulevé de terre sumo haltères', 'glutes', '{quads,hamstrings}', 'dumbbell', 'compound', 'Wide stance, toes out. Dumbbell hanging between legs. Hinge and bend knees. Stand by driving hips forward.', 'Position large, pointes écartées. Haltère entre les jambes. Penchez-vous. Levez-vous en poussant les hanches.', 'beginner', 'hinge'),
('Dumbbell Single-Leg Hip Thrust', 'Hip thrust unilatéral haltère', 'glutes', '{hamstrings}', 'dumbbell', 'compound', 'Upper back on bench, one foot on floor, other leg extended. Dumbbell on hip. Drive up on single leg. Squeeze glute.', 'Dos sur le banc, un pied au sol, l''autre tendu. Haltère sur la hanche. Poussez sur une jambe. Contractez.', 'intermediate', 'hinge'),
('Cable Hip Abduction', 'Abduction hanche poulie', 'glutes', '{}', 'cable', 'isolation', 'Ankle cuff on low pulley. Stand sideways, raise leg outward against resistance. Squeeze glute medius. Slow return.', 'Bracelet de cheville, poulie basse. De côté, montez la jambe vers l''extérieur. Contractez le moyen fessier. Retour lent.', 'beginner', 'isolation'),
('Cable Hip Adduction', 'Adduction hanche poulie', 'glutes', '{}', 'cable', 'isolation', 'Ankle cuff on low pulley. Stand sideways, pull leg across body against resistance. Squeeze inner thigh. Slow return.', 'Bracelet de cheville, poulie basse. De côté, tirez la jambe vers l''intérieur. Contractez l''intérieur de la cuisse. Retour lent.', 'beginner', 'isolation'),
('Machine Hip Adduction', 'Adduction hanche machine', 'glutes', '{}', 'machine', 'isolation', 'Sit in machine, pads on inner thighs. Squeeze legs together against resistance. Slow return. Targets adductors.', 'Assis, pads sur l''intérieur des cuisses. Serrez les jambes. Retour lent. Cible les adducteurs.', 'beginner', 'isolation'),
('Machine Glute Kickback', 'Kickback fessier machine', 'glutes', '{hamstrings}', 'machine', 'isolation', 'Stand in machine, foot on platform. Kick leg back against resistance. Squeeze glute at full extension. Slow return.', 'Debout, pied sur la plateforme. Poussez la jambe en arrière. Contractez le fessier en extension. Retour lent.', 'beginner', 'isolation'),
('Machine Hip Thrust', 'Hip thrust machine', 'glutes', '{hamstrings}', 'machine', 'compound', 'Sit in hip thrust machine. Drive hips up against resistance. Squeeze glutes at top. Lower with control. No setup hassle.', 'Assis dans la machine. Poussez les hanches contre la résistance. Contractez. Descendez avec contrôle. Pas de mise en place.', 'beginner', 'hinge'),
('Smith Machine Hip Thrust', 'Hip thrust Smith machine', 'glutes', '{hamstrings}', 'machine', 'compound', 'Upper back on bench, Smith bar over hips. Drive hips up along guided path. Squeeze glutes. Lower with control.', 'Dos sur le banc, barre Smith sur les hanches. Poussez le long du rail. Contractez les fessiers. Descendez avec contrôle.', 'beginner', 'hinge'),
('Donkey Kick', 'Coup de pied âne', 'glutes', '{}', 'bodyweight', 'isolation', 'On all fours. Kick one leg back and up, knee bent at 90°. Squeeze glute at top. Lower with control. Keep core engaged.', 'À quatre pattes. Poussez une jambe en arrière et vers le haut, genou à 90°. Contractez. Descendez avec contrôle. Gainez.', 'beginner', 'isolation'),
('Fire Hydrant', 'Bouche d''incendie', 'glutes', '{}', 'bodyweight', 'isolation', 'On all fours. Raise knee out to the side, hip at 90°. Squeeze glute medius. Lower with control. Keep core stable.', 'À quatre pattes. Montez le genou sur le côté. Contractez le moyen fessier. Descendez avec contrôle. Gainage stable.', 'beginner', 'isolation'),
('Lateral Band Walk', 'Marche latérale avec bande', 'glutes', '{}', 'bands', 'isolation', 'Band around ankles or above knees. Quarter squat position. Step sideways, maintaining tension. Keep toes forward. Great for activation.', 'Bande aux chevilles ou au-dessus des genoux. Position quart de squat. Pas latéraux en maintenant la tension. Excellent pour l''activation.', 'beginner', 'isolation'),
('Cossack Squat', 'Squat cosaque', 'glutes', '{quads,hamstrings}', 'bodyweight', 'compound', 'Wide stance. Shift weight to one side, squat deep on that leg. Other leg stays straight, toes up. Alternate sides. Great for mobility and strength.', 'Position large. Déplacez le poids d''un côté, descendez. L''autre jambe reste droite. Alternez. Excellent pour la mobilité.', 'intermediate', 'squat'),
('Band Glute Kickback', 'Kickback fessier avec bande', 'glutes', '{}', 'bands', 'isolation', 'Band around ankles. On all fours or standing. Kick one leg back against resistance. Squeeze glute. Slow return.', 'Bande aux chevilles. À quatre pattes ou debout. Poussez une jambe en arrière. Contractez le fessier. Retour lent.', 'beginner', 'isolation'),
('Band Clamshell', 'Clamshell avec bande', 'glutes', '{}', 'bands', 'isolation', 'Lie on side, band above knees, knees bent. Open top knee like a clamshell against resistance. Keep feet together. Squeeze.', 'Allongé sur le côté, bande au-dessus des genoux. Ouvrez le genou supérieur. Gardez les pieds ensemble. Contractez.', 'beginner', 'isolation'),
('Kettlebell Lateral Lunge', 'Fente latérale kettlebell', 'glutes', '{quads}', 'kettlebell', 'compound', 'Hold kettlebell at chest. Step wide to one side, sit hips back. Push back to start through planted foot. Alternate sides.', 'Kettlebell à la poitrine. Grand pas latéral, reculez les hanches. Revenez en poussant. Alternez les côtés.', 'intermediate', 'squat'),
('Dumbbell Glute Bridge', 'Pont fessier haltère', 'glutes', '{hamstrings}', 'dumbbell', 'isolation', 'Lie on floor, dumbbell over hips. Feet flat, knees bent. Drive hips up, squeeze glutes. Lower with control.', 'Allongé, haltère sur les hanches. Pieds à plat. Poussez les hanches, contractez. Descendez avec contrôle.', 'beginner', 'isolation');

-- ============================================================================
-- CALVES (+9 new → 20 total)
-- ============================================================================
INSERT INTO public.exercises (name_en, name_fr, muscle_primary, muscle_secondary, equipment, category, cues_en, cues_fr, difficulty, movement_pattern) VALUES
('Barbell Seated Calf Raise', 'Mollets assis barre', 'calves', '{}', 'barbell', 'isolation', 'Sit on bench, barbell on knees. Raise heels as high as possible. Squeeze calves at top. Lower slowly for full stretch.', 'Assis, barre sur les genoux. Montez les talons au maximum. Contractez. Descendez lentement pour l''étirement complet.', 'intermediate', 'isolation'),
('Dumbbell Single-Leg Calf Raise', 'Mollets unilatéral haltère', 'calves', '{}', 'dumbbell', 'isolation', 'Hold dumbbell in one hand, stand on one foot on step edge. Raise heel high. Squeeze calf. Lower below step level for full stretch.', 'Haltère en main, debout sur un pied au bord d''une marche. Montez le talon. Contractez. Descendez sous la marche.', 'intermediate', 'isolation'),
('Cable Seated Calf Raise', 'Mollets assis poulie', 'calves', '{}', 'cable', 'isolation', 'Sit at low pulley, attachment over knees. Raise heels against cable resistance. Squeeze calves at top. Slow negative.', 'Assis à la poulie basse, attache sur les genoux. Montez les talons. Contractez. Négatif lent.', 'beginner', 'isolation'),
('Machine Donkey Calf Raise', 'Mollets ânesse machine', 'calves', '{}', 'machine', 'isolation', 'Bend at hips in donkey calf machine, pad on lower back. Raise heels as high as possible. Squeeze. Full stretch at bottom.', 'Penché dans la machine, pad sur le bas du dos. Montez les talons au maximum. Contractez. Étirement complet en bas.', 'intermediate', 'isolation'),
('Smith Machine Calf Raise', 'Mollets debout Smith machine', 'calves', '{}', 'machine', 'isolation', 'Bar on upper back in Smith machine, balls of feet on raised surface. Raise heels high. Squeeze. Lower for full stretch.', 'Barre sur le dos, avant-pieds sur une surface surélevée. Montez les talons. Contractez. Descendez pour l''étirement.', 'beginner', 'isolation'),
('Bodyweight Calf Raise', 'Mollets debout au poids du corps', 'calves', '{}', 'bodyweight', 'isolation', 'Stand on both feet, optionally on step edge. Raise heels as high as possible. Squeeze calves. Lower with control.', 'Debout sur les deux pieds, optionnellement au bord d''une marche. Montez les talons. Contractez. Descendez avec contrôle.', 'beginner', 'isolation'),
('Seated Bodyweight Calf Raise', 'Mollets assis au poids du corps', 'calves', '{}', 'bodyweight', 'isolation', 'Sit on bench, feet flat. Place weight or use bodyweight. Raise heels high, squeezing calves. Lower with control. Targets soleus.', 'Assis sur un banc, pieds à plat. Montez les talons en contractant. Descendez avec contrôle. Cible le soléaire.', 'beginner', 'isolation'),
('Eccentric Heel Drop', 'Descente excentrique du talon', 'calves', '{}', 'bodyweight', 'isolation', 'Stand on step edge on one foot. Slowly lower heel below step level over 3-5 seconds. Use other foot to push back up. Excellent for tendon health.', 'Debout au bord d''une marche sur un pied. Descendez lentement le talon sur 3-5 secondes. Remontez avec l''autre pied. Excellent pour les tendons.', 'beginner', 'isolation'),
('Kettlebell Seated Calf Raise', 'Mollets assis kettlebell', 'calves', '{}', 'kettlebell', 'isolation', 'Sit on bench, kettlebell on knees. Raise heels as high as possible. Squeeze calves. Lower slowly. Targets soleus.', 'Assis, kettlebell sur les genoux. Montez les talons. Contractez. Descendez lentement. Cible le soléaire.', 'beginner', 'isolation');

-- ============================================================================
-- ABS (+32 new → 50 total)
-- ============================================================================
INSERT INTO public.exercises (name_en, name_fr, muscle_primary, muscle_secondary, equipment, category, cues_en, cues_fr, difficulty, movement_pattern) VALUES
('Crunch', 'Crunch', 'abs', '{}', 'bodyweight', 'isolation', 'Lie on back, knees bent, hands behind head. Curl shoulders off floor, squeezing abs. Lower with control. Do not pull on neck.', 'Allongé, genoux fléchis, mains derrière la tête. Soulevez les épaules en contractant. Descendez avec contrôle. Ne tirez pas sur le cou.', 'beginner', 'isolation'),
('Sit-Up', 'Relevé de buste', 'abs', '{hip_flexors}', 'bodyweight', 'isolation', 'Lie on back, knees bent, feet anchored. Sit all the way up, then lower with control. Engages hip flexors more than crunches.', 'Allongé, genoux fléchis, pieds bloqués. Montez complètement, descendez avec contrôle. Engage plus les fléchisseurs de hanche.', 'beginner', 'isolation'),
('Side Plank', 'Planche latérale', 'abs', '{}', 'bodyweight', 'isolation', 'Lie on side, forearm on floor. Raise hips until body forms straight line. Hold position. Breathe steadily. Switch sides.', 'Allongé sur le côté, avant-bras au sol. Montez les hanches en ligne droite. Maintenez. Respirez. Changez de côté.', 'beginner', 'isolation'),
('Dead Bug', 'Dead bug', 'abs', '{}', 'bodyweight', 'isolation', 'Lie on back, arms up, knees at 90°. Extend opposite arm and leg while keeping lower back pressed to floor. Return and alternate.', 'Allongé, bras en l''air, genoux à 90°. Étendez bras et jambe opposés en gardant le bas du dos au sol. Alternez.', 'beginner', 'isolation'),
('Hollow Hold', 'Hollow hold', 'abs', '{}', 'bodyweight', 'isolation', 'Lie on back. Arms overhead, legs straight. Raise shoulders and legs slightly off floor. Hold. Lower back must stay pressed to floor.', 'Allongé. Bras au-dessus, jambes droites. Soulevez épaules et jambes légèrement. Maintenez. Bas du dos collé au sol.', 'intermediate', 'isolation'),
('V-Up', 'V-up', 'abs', '{}', 'bodyweight', 'isolation', 'Lie flat, arms overhead. Simultaneously lift legs and torso to form a V. Reach hands toward toes. Lower with control.', 'Allongé, bras au-dessus. Soulevez jambes et torse simultanément en V. Touchez les orteils. Descendez avec contrôle.', 'intermediate', 'isolation'),
('Lying Leg Raise', 'Relevé de jambes allongé', 'abs', '{}', 'bodyweight', 'isolation', 'Lie on back, hands under hips. Raise straight legs to vertical. Lower slowly without touching floor. Keep lower back pressed down.', 'Allongé, mains sous les hanches. Montez les jambes droites. Descendez lentement sans toucher le sol. Dos plaqué.', 'intermediate', 'isolation'),
('Hanging Knee Raise', 'Relevé de genoux suspendu', 'abs', '{}', 'bodyweight', 'isolation', 'Hang from bar, arms straight. Raise knees toward chest. Squeeze abs at top. Lower with control. Avoid swinging.', 'Suspendu, bras tendus. Montez les genoux vers la poitrine. Contractez. Descendez avec contrôle. Évitez le balancement.', 'intermediate', 'isolation'),
('Oblique Crunch', 'Crunch oblique', 'abs', '{}', 'bodyweight', 'isolation', 'Lie on back, one ankle on opposite knee. Crunch toward raised knee, rotating torso. Lower with control. Switch sides.', 'Allongé, une cheville sur le genou opposé. Crunchez en rotation vers le genou levé. Descendez. Changez de côté.', 'beginner', 'rotation'),
('Reverse Crunch', 'Crunch inversé', 'abs', '{}', 'bodyweight', 'isolation', 'Lie on back, knees bent at 90°. Pull knees toward chest, lifting hips off floor. Lower with control. Targets lower abs.', 'Allongé, genoux à 90°. Tirez les genoux vers la poitrine, soulevez les hanches. Descendez. Cible les abdos bas.', 'beginner', 'isolation'),
('Flutter Kick', 'Battement de jambes', 'abs', '{}', 'bodyweight', 'isolation', 'Lie on back, legs straight, slightly raised. Alternate small up-and-down kicks. Keep lower back pressed to floor. Breathe steadily.', 'Allongé, jambes droites légèrement levées. Alternez de petits battements. Gardez le bas du dos au sol. Respirez.', 'beginner', 'isolation'),
('Toe Touch Crunch', 'Crunch toucher les orteils', 'abs', '{}', 'bodyweight', 'isolation', 'Lie on back, legs vertical. Crunch up and reach toward toes. Squeeze abs at top. Lower with control.', 'Allongé, jambes verticales. Montez et touchez les orteils. Contractez. Descendez avec contrôle.', 'beginner', 'isolation'),
('Scissor Kick', 'Ciseaux', 'abs', '{}', 'bodyweight', 'isolation', 'Lie on back, legs slightly raised. Cross legs alternately in a scissor motion. Keep lower back pressed to floor. Controlled tempo.', 'Allongé, jambes légèrement levées. Croisez les jambes alternativement en ciseaux. Dos au sol. Tempo contrôlé.', 'beginner', 'isolation'),
('Decline Sit-Up', 'Relevé de buste décliné', 'abs', '{}', 'bodyweight', 'isolation', 'Lie on decline bench, feet hooked. Sit all the way up, then lower with control. Increased range challenges abs more.', 'Allongé sur banc décliné, pieds bloqués. Montez complètement. Descendez avec contrôle. L''amplitude augmentée est plus exigeante.', 'intermediate', 'isolation'),
('Bear Crawl', 'Marche de l''ours', 'abs', '{shoulders,quads}', 'bodyweight', 'compound', 'On all fours, knees hovering just above floor. Crawl forward moving opposite hand and foot. Keep back flat and core tight.', 'À quatre pattes, genoux au-dessus du sol. Avancez en déplaçant main et pied opposés. Dos plat et gainage.', 'intermediate', 'isolation'),
('Plank Shoulder Tap', 'Planche avec toucher d''épaule', 'abs', '{shoulders}', 'bodyweight', 'isolation', 'High plank position. Tap opposite shoulder with one hand while maintaining stable hips. Alternate sides. Anti-rotation core work.', 'Position de planche haute. Touchez l''épaule opposée en maintenant les hanches stables. Alternez. Travail anti-rotation.', 'intermediate', 'isolation'),
('Bird Dog', 'Bird dog', 'abs', '{back,glutes}', 'bodyweight', 'isolation', 'On all fours. Extend opposite arm and leg simultaneously. Hold briefly. Return with control. Alternate sides. Core stability exercise.', 'À quatre pattes. Étendez bras et jambe opposés. Maintenez. Revenez avec contrôle. Alternez. Exercice de stabilité.', 'beginner', 'isolation'),
('Bodyweight Russian Twist', 'Rotation russe au poids du corps', 'abs', '{}', 'bodyweight', 'isolation', 'Sit with torso leaned back, feet off floor. Rotate torso side to side, touching floor beside hips. Keep feet elevated.', 'Assis, torse penché en arrière, pieds levés. Tournez le torse de chaque côté en touchant le sol. Gardez les pieds levés.', 'beginner', 'rotation'),
('Copenhagen Plank', 'Planche de Copenhague', 'abs', '{glutes}', 'bodyweight', 'isolation', 'Side plank with top leg on bench, bottom leg free. Hold position. Targets obliques and adductors. Switch sides.', 'Planche latérale avec la jambe supérieure sur un banc, l''autre libre. Maintenez. Cible obliques et adducteurs. Changez.', 'advanced', 'isolation'),
('Windshield Wiper', 'Essuie-glace', 'abs', '{}', 'bodyweight', 'isolation', 'Lie on back, arms out for support, legs vertical. Rotate legs side to side like windshield wipers. Control the motion. Advanced rotational core.', 'Allongé, bras écartés, jambes verticales. Tournez les jambes de chaque côté comme des essuie-glaces. Contrôlez le mouvement.', 'intermediate', 'rotation'),
('Toes-to-Bar', 'Orteils à la barre', 'abs', '{}', 'bodyweight', 'compound', 'Hang from bar. Raise straight legs until toes touch bar. Lower with control. Requires strong hip flexors and core. Avoid kipping.', 'Suspendu. Montez les jambes tendues jusqu''à ce que les orteils touchent la barre. Descendez. Nécessite un gainage fort.', 'advanced', 'isolation'),
('Captain''s Chair Leg Raise', 'Relevé de jambes chaise romaine', 'abs', '{}', 'machine', 'isolation', 'Support yourself on captain''s chair pads, back against pad. Raise legs to parallel or higher. Lower with control. Do not swing.', 'Supportez-vous sur les pads, dos contre le support. Montez les jambes à la parallèle. Descendez avec contrôle. Pas de balancement.', 'intermediate', 'isolation'),
('Captain''s Chair Knee Raise', 'Relevé de genoux chaise romaine', 'abs', '{}', 'machine', 'isolation', 'Support yourself on captain''s chair. Raise knees toward chest. Squeeze abs. Lower with control. Easier than leg raise.', 'Supportez-vous sur la chaise. Montez les genoux vers la poitrine. Contractez. Descendez avec contrôle. Plus facile que le relevé de jambes.', 'beginner', 'isolation'),
('Landmine Rotation', 'Rotation landmine', 'abs', '{shoulders}', 'barbell', 'compound', 'Hold barbell end at chest, other end anchored. Rotate bar from side to side in an arc. Control the motion. Powerful rotational core exercise.', 'Tenez le bout de la barre à la poitrine, l''autre bout ancré. Tournez en arc de chaque côté. Contrôlez. Puissant travail de rotation.', 'intermediate', 'rotation'),
('Cable Side Bend', 'Flexion latérale poulie', 'abs', '{}', 'cable', 'isolation', 'Stand sideways to low pulley. Bend away from cable, stretching oblique. Return with control. Keep hips still. Switch sides.', 'De côté à la poulie basse. Penchez-vous à l''opposé. Revenez avec contrôle. Gardez les hanches fixes. Changez de côté.', 'beginner', 'isolation'),
('Dumbbell Woodchop', 'Woodchop haltère', 'abs', '{shoulders}', 'dumbbell', 'compound', 'Hold dumbbell at one hip. Chop diagonally across body to opposite shoulder. Control the return. Rotate through core, not arms.', 'Haltère à une hanche. Coupez en diagonale vers l''épaule opposée. Retour contrôlé. Tournez avec le tronc, pas les bras.', 'intermediate', 'rotation'),
('Dumbbell Suitcase Carry', 'Portage valise haltère', 'abs', '{forearms}', 'dumbbell', 'compound', 'Hold heavy dumbbell in one hand at side. Walk while resisting lateral lean. Keep torso upright. Switch sides. Anti-lateral flexion.', 'Tenez un haltère lourd d''un côté. Marchez en résistant à l''inclinaison. Gardez le torse droit. Changez de côté.', 'intermediate', 'carry'),
('Kettlebell Suitcase Carry', 'Portage valise kettlebell', 'abs', '{forearms}', 'kettlebell', 'compound', 'Hold heavy kettlebell in one hand. Walk while maintaining upright posture. Resist lateral lean. Switch sides. Core stability.', 'Tenez un kettlebell lourd d''un côté. Marchez en restant droit. Résistez à l''inclinaison. Changez de côté. Stabilité du tronc.', 'intermediate', 'carry'),
('Band Crunch', 'Crunch avec bande', 'abs', '{}', 'bands', 'isolation', 'Anchor band behind you overhead. Hold at neck level. Crunch forward against resistance. Squeeze abs. Slow return.', 'Ancrez la bande derrière en hauteur. Tenez au niveau du cou. Crunchez en avant contre la résistance. Contractez. Retour lent.', 'beginner', 'isolation'),
('Decline Reverse Crunch', 'Crunch inversé décliné', 'abs', '{}', 'bodyweight', 'isolation', 'Lie on decline bench, head at top, grip bench. Pull knees toward chest, lifting hips. Lower with control. Increased difficulty.', 'Allongé sur banc décliné, tête en haut. Tirez les genoux, soulevez les hanches. Descendez avec contrôle. Difficulté augmentée.', 'intermediate', 'isolation'),
('Hanging Windshield Wiper', 'Essuie-glace suspendu', 'abs', '{}', 'bodyweight', 'compound', 'Hang from bar, raise legs to 90°. Rotate legs side to side while maintaining height. Extremely demanding core exercise.', 'Suspendu, montez les jambes à 90°. Tournez de chaque côté en maintenant la hauteur. Exercice extrêmement exigeant.', 'advanced', 'rotation'),
('Weighted Plank', 'Planche lestée', 'abs', '{}', 'bodyweight', 'isolation', 'Standard plank position with weight plate on upper back. Hold position with straight body. Breathe steadily. Build time gradually.', 'Position de planche avec disque sur le haut du dos. Maintenez le corps droit. Respirez. Augmentez progressivement.', 'intermediate', 'isolation');

-- ============================================================================
-- TRAPS (+10 new → 20 total)
-- ============================================================================
INSERT INTO public.exercises (name_en, name_fr, muscle_primary, muscle_secondary, equipment, category, cues_en, cues_fr, difficulty, movement_pattern) VALUES
('Barbell Behind-the-Back Shrug', 'Shrug derrière le dos barre', 'traps', '{}', 'barbell', 'isolation', 'Hold barbell behind you, shoulder-width grip. Shrug shoulders up toward ears. Squeeze at top. Lower with control.', 'Barre derrière le dos, prise largeur d''épaules. Haussez les épaules vers les oreilles. Contractez. Descendez avec contrôle.', 'intermediate', 'isolation'),
('Barbell Power Shrug', 'Shrug puissance barre', 'traps', '{}', 'barbell', 'compound', 'Barbell at thighs. Use slight knee dip to explosively shrug weight. Hold briefly at top. Lower with control. Heavier loads than strict shrugs.', 'Barre aux cuisses. Légère flexion des genoux pour hausser explossivement. Maintenez en haut. Descendez. Charges plus lourdes.', 'intermediate', 'isolation'),
('Dumbbell Upright Row', 'Rowing vertical haltères', 'traps', '{shoulders}', 'dumbbell', 'compound', 'Dumbbells in front of thighs. Pull up along body, elbows high and wide. Lower with control. Do not go above shoulder height.', 'Haltères devant les cuisses. Tirez vers le haut, coudes hauts et écartés. Descendez. Ne dépassez pas les épaules.', 'beginner', 'pull'),
('Dumbbell Prone Shrug', 'Shrug pronation haltères', 'traps', '{}', 'dumbbell', 'isolation', 'Lie face down on incline bench. Arms hanging with dumbbells. Squeeze shoulder blades together and up. Hold. Lower with control. Targets lower traps.', 'Allongé face vers le bas sur banc incliné. Bras pendants avec haltères. Serrez les omoplates ensemble et vers le haut. Cible les trapèzes bas.', 'beginner', 'isolation'),
('Smith Machine Shrug', 'Shrug Smith machine', 'traps', '{}', 'machine', 'isolation', 'Grip Smith bar at thighs. Shrug shoulders up along guided path. Squeeze at top. Lower with control. Allows focus on pure shrugging.', 'Saisissez la barre Smith. Haussez les épaules le long du rail. Contractez. Descendez avec contrôle. Permet de se concentrer sur le mouvement.', 'beginner', 'isolation'),
('Kettlebell Shrug', 'Shrug kettlebell', 'traps', '{}', 'kettlebell', 'isolation', 'Hold kettlebells at sides. Shrug shoulders toward ears. Squeeze at top. Lower with control. Offset center of mass challenges grip.', 'Kettlebells le long du corps. Haussez les épaules vers les oreilles. Contractez. Descendez avec contrôle.', 'beginner', 'isolation'),
('Kettlebell Upright Row', 'Rowing vertical kettlebell', 'traps', '{shoulders}', 'kettlebell', 'compound', 'Kettlebell in front of thighs. Pull up along body, elbows high. Lower with control. The offset weight adds a stability challenge.', 'Kettlebell devant les cuisses. Tirez vers le haut, coudes hauts. Descendez avec contrôle. Le poids décalé ajoute un défi de stabilité.', 'beginner', 'pull'),
('Band Upright Row', 'Rowing vertical avec bande', 'traps', '{shoulders}', 'bands', 'compound', 'Stand on band, grip handles close. Pull up along body, elbows high. Lower with control. Increasing resistance through range.', 'Debout sur la bande, prise serrée. Tirez vers le haut, coudes hauts. Descendez avec contrôle. Résistance croissante.', 'beginner', 'pull'),
('Cable Shrug Behind Back', 'Shrug derrière le dos poulie', 'traps', '{}', 'cable', 'isolation', 'Low pulley behind you, bar attachment. Shrug shoulders up and slightly back. Squeeze at top. Lower with control.', 'Poulie basse derrière, barre attachée. Haussez les épaules vers le haut et l''arrière. Contractez. Descendez avec contrôle.', 'beginner', 'isolation'),
('Dumbbell Overhead Shrug', 'Shrug au-dessus haltères', 'traps', '{}', 'dumbbell', 'isolation', 'Hold dumbbells overhead, arms locked. Shrug shoulders up toward ceiling. Squeeze. Lower with control. Targets lower and mid traps.', 'Haltères au-dessus, bras verrouillés. Haussez les épaules vers le plafond. Contractez. Descendez. Cible les trapèzes bas et moyens.', 'intermediate', 'isolation');

-- ============================================================================
-- FOREARMS (+10 new → 21 total)
-- ============================================================================
INSERT INTO public.exercises (name_en, name_fr, muscle_primary, muscle_secondary, equipment, category, cues_en, cues_fr, difficulty, movement_pattern) VALUES
('Barbell Behind-the-Back Wrist Curl', 'Curl poignet derrière le dos barre', 'forearms', '{}', 'barbell', 'isolation', 'Hold barbell behind back. Curl wrists upward by flexing forearms. Squeeze at top. Lower with control. Allows heavier loads.', 'Barre derrière le dos. Fléchissez les poignets vers le haut. Contractez. Descendez avec contrôle. Permet des charges plus lourdes.', 'intermediate', 'isolation'),
('Barbell Wrist Roller', 'Rouleau à poignet barre', 'forearms', '{}', 'barbell', 'isolation', 'Hold bar with rope and weight attached. Roll weight up by alternating wrist rotations. Then roll back down. Brutal forearm endurance.', 'Barre avec corde et poids. Enroulez en alternant les rotations de poignet. Puis déroulez. Endurance extrême des avant-bras.', 'intermediate', 'isolation'),
('Dumbbell Pronation Supination', 'Pronation supination haltère', 'forearms', '{}', 'dumbbell', 'isolation', 'Hold dumbbell by one end, arm on bench. Rotate forearm from palm up to palm down. Slow and controlled. Strengthens rotator muscles.', 'Tenez l''haltère par un bout, bras sur le banc. Tournez l''avant-bras de paume vers le haut à paume vers le bas. Lent et contrôlé.', 'beginner', 'rotation'),
('Dumbbell Finger Curl', 'Curl des doigts haltère', 'forearms', '{}', 'dumbbell', 'isolation', 'Hold dumbbell, let it roll to fingertips. Curl fingers to close grip, then flex wrist up. Squeeze. Lower and repeat.', 'Tenez l''haltère, laissez-le rouler aux doigts. Fermez les doigts, puis fléchissez le poignet. Contractez. Recommencez.', 'beginner', 'isolation'),
('Cable Reverse Curl', 'Curl inversé poulie', 'forearms', '{biceps}', 'cable', 'isolation', 'Low pulley, straight bar, overhand grip. Curl up keeping wrists straight. Lower with control. Targets brachioradialis.', 'Poulie basse, barre droite, prise pronation. Montez en gardant les poignets droits. Descendez. Cible le brachio-radial.', 'beginner', 'pull'),
('Cable Wrist Extension', 'Extension poignet poulie', 'forearms', '{}', 'cable', 'isolation', 'Low pulley, forearms on bench, palms down. Extend wrists upward against resistance. Lower with control. Targets wrist extensors.', 'Poulie basse, avant-bras sur le banc, paumes vers le bas. Étendez les poignets vers le haut. Descendez. Cible les extenseurs.', 'beginner', 'isolation'),
('Bodyweight Towel Hang', 'Suspension serviette', 'forearms', '{}', 'bodyweight', 'isolation', 'Drape towel over pull-up bar. Grip towel ends and hang. Hold as long as possible. Extreme grip challenge. Build time gradually.', 'Drapez une serviette sur une barre. Saisissez les extrémités et suspendez-vous. Tenez le plus longtemps possible. Défi de prise extrême.', 'intermediate', 'isolation'),
('Bodyweight Fingertip Push-Up', 'Pompes sur les doigts', 'forearms', '{chest,triceps}', 'bodyweight', 'compound', 'Push-up position on fingertips instead of palms. Lower and press up. Strengthens fingers and forearms. Start on knees if needed.', 'Position de pompes sur les doigts au lieu des paumes. Descendez et remontez. Renforce les doigts. Commencez sur les genoux si nécessaire.', 'advanced', 'push'),
('Kettlebell Wrist Curl', 'Curl poignet kettlebell', 'forearms', '{}', 'kettlebell', 'isolation', 'Forearm on bench, hold kettlebell by handle, palm up. Curl wrist upward. Squeeze. Lower with control. Offset weight adds challenge.', 'Avant-bras sur le banc, kettlebell en main, paume vers le haut. Fléchissez le poignet. Contractez. Le poids décalé ajoute un défi.', 'beginner', 'isolation'),
('Band Wrist Curl', 'Curl poignet avec bande', 'forearms', '{}', 'bands', 'isolation', 'Anchor band low, grip with palm up. Curl wrist against resistance. Squeeze at top. Slow return. Constant tension.', 'Ancrez la bande en bas, paume vers le haut. Fléchissez le poignet contre la résistance. Contractez. Retour lent.', 'beginner', 'isolation');
